### ISSUE TITLE
Apply the model to my own dataset

### ISSUE THREAD

**Issue by Xingyi0220** [2gunsu/monocon-pytorch#13]

**Comment by Xingyi0220** [comment]
Hello Author! Thank you so much for your contribution. I am trying to use the model to do the inference of my own data. I put a camera just inside the car and it is put front middle. And I did rough calibration of the camera(only intrinsic one)... Under this condition, I don't have idea how to apply it. I will be super grateful if you can give me some suggestions.

**Comment by 2gunsu** [comment]
Hello. Sorry for the very late reply.
I will think a little more about what you said and respond.

I'm sorry. 😭
