### ISSUE TITLE
multi-gpu train

### ISSUE THREAD

**Issue by happyday-lkj** [2gunsu/monocon-pytorch#16]
whether do you plan to support multi-gpu training???

**Comment by 2gunsu** [comment]
Hello. I'm sorry for the late response. 
There is a code with the Multi-GPU function added as you mentioned, but the current code itself is not organized enough, so I will update it later. Thank you.

**Comment by QSQSQSQS** [comment]
@2gunsu could you please release the multi-gpu code? I really need this ,thanks!
