### ISSUE TITLE
How to train on nuscenes?

### ISSUE THREAD

**Issue by Lyric0620** [2gunsu/monocon-pytorch#18]
How can i train monocon on nuscenes dataset?

**Comment by 2gunsu** [comment]
Hello. I'm sorry for the late response. 
This code is currently written with only KITTI data in mind and is not compatible with the Nuscenes dataset. I will update you if I have a GPU available in the future. Thank you.

**Comment by Lyric0620** [comment]
@2gunsu I convert nuscenes dataset to kitti format. But I meet this problem when train
```
  File "/hy-tmp/monocon-pytorch/losses/l1_loss.py", line 17, in l1_loss
    assert pred.size() == target.size() and target.numel() > 0
AssertionError
```
then I print `pred` and `target`
```
tensor([], device='cuda:0', size=(0, 2), grad_fn=<IndexBackward0>)
tensor([], device='cuda:0', size=(0, 2))
```
How can I solve this problem.

**Comment by ycdhqzhiai** [comment]
> [@2gunsu](https://github.com/2gunsu) I convert nuscenes dataset to kitti format. But I meet this problem when train
> 
> ```
>   File "/hy-tmp/monocon-pytorch/losses/l1_loss.py", line 17, in l1_loss
>     assert pred.size() == target.size() and target.numel() > 0
> AssertionError
> ```
> 
> then I print `pred` and `target`
> 
> ```
> tensor([], device='cuda:0', size=(0, 2), grad_fn=<IndexBackward0>)
> tensor([], device='cuda:0', size=(0, 2))
> ```
> 
> How can I solve this problem.

@Yutong-gannis  Have you solved this problem
