### ISSUE TITLE
The Best Random Seed

### ISSUE THREAD

**Issue by kwong292521** [2gunsu/monocon-pytorch#19]
Firstly, I would like to express my appreciation for your valuable contributions to this code.

As I was going through your code, I noticed that you have trained several models and achieved excellent results. I am particularly interested in the best-performing model that you have reported in your paper. However, I couldn't find any information regarding the random seed used to train the model.

I would appreciate it if you could kindly share the random seed used to train your best model. This information will be helpful for me to reproduce your results and compare them with my own experiments.

Thank you for your time and consideration.

**Comment by 2gunsu** [comment]
Hello. I'm sorry for the late response.

Unfortunately, the best performance came from the model that ran the training without fixing the seed. And at that time, the code didn't have the function to log training seeds, so there's no way to know them again at this time. 😭

I will reply to you again if I find out.

**Comment by 2gunsu** [comment]
Close issue due to inactivity. If you have another question, feel free to reopen it.
