### ISSUE TITLE
assertionerror

### ISSUE THREAD

**Issue by LionGx** [2gunsu/monocon-pytorch#2]
Thank you for your awsome work!

I changed the assert in l1_loss.l1_loss into:

"assert pred.size() == target.size(), "pred.size() != target.size()"
 assert target.numel() > 0, "target.numel() = 0"

and this error ocurred:

Traceback (most recent call last):
  File "/home/gx/code/monocon-pytorch-main/train.py", line 34, in <module>
    engine.train()
  File "/home/gx/code/monocon-pytorch-main/engine/base_engine.py", line 115, in train
    avg_loss, elapsed_time = self.train_one_epoch()
  File "/home/gx/code/monocon-pytorch-main/utils/decorators.py", line 7, in wrapper
    result = function(*args, **kwargs)
  File "/home/gx/code/monocon-pytorch-main/engine/monocon_engine.py", line 80, in train_one_epoch
    _, loss_dict = self.model(data_dict)
  File "/home/gx/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/gx/code/monocon-pytorch-main/model/detector/monocon_detector.py", line 52, in forward
    pred_dict, loss_dict = self.head.forward_train(feat, data_dict)
  File "/home/gx/code/monocon-pytorch-main/model/dense_heads/monocon_heads.py", line 148, in forward_train
    loss_dict = self._get_losses(pred_dict, target_dict)
  File "/home/gx/code/monocon-pytorch-main/model/dense_heads/monocon_heads.py", line 211, in _get_losses
    offset_loss = self.crit_offset(offset_pred, offset_target)
  File "/home/gx/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/gx/code/monocon-pytorch-main/losses/l1_loss.py", line 40, in forward
    return self.loss_weight * l1_loss(pred, target, weight, reduction=reduction, avg_factor=avg_factor)
  File "/home/gx/code/monocon-pytorch-main/losses/utils.py", line 46, in wrapper
    loss = loss_func(pred, target, **kwargs)
  File "/home/gx/code/monocon-pytorch-main/losses/l1_loss.py", line 16, in l1_loss
    assert target.numel() > 0, "target.numel() = 0"
AssertionError: target.numel() = 0

Is it bacause "target.numel() == 0"? How to solve it?
Thank you so much!

**Comment by 2gunsu** [comment]
Hello. Thanks for your interest in my code. 😊
I understood that an error occurred when the ```l1_loss``` function in ```losses/l1_loss.py``` was modified as follows. Am I correct?

```python
@weighted_loss
def l1_loss(pred: torch.Tensor, target: torch.Tensor) -> torch.Tensor:
    assert pred.size() == target.size(), "pred.size() != target.size()"
    assert target.numel() > 0, "target.numel() == 0"
    loss = torch.abs(pred - target)
    return loss
```

**Comment by LionGx** [comment]
It occurred while running train.py, why would target.numel() ==0? and how to solve it?

**Comment by 2gunsu** [comment]
I've found that I get the exact same error you mentioned when the batch size is set small. What value did you set the batch size to? I wonder if you used the default value of 8 as it is.

**Comment by LionGx** [comment]
Got it! I used 2 because my gpu memory is too small.
Thank you so much!

**Comment by 2gunsu** [comment]
I think I can suggest three solutions below.
You might want to pick one of these and give it a try.

1. Try setting the **batch size to a larger value**. As the batch size increases, the probability that the target data of the corresponding mini-batch is empty is significantly reduced and will not cause errors.

2. If you can't change the batch size due to limited GPU memory, don't use ```RandomCrop3D```, one of the transformations that erases objects present in the image. Set ```default_train_transforms``` in ```dataset/monocon_dataset.py``` as below.
```python
default_train_transforms = [
    PhotometricDistortion(
        brightness_delta=32,
        contrast_range=(0.5, 1.5),
        saturation_range=(0.5, 1.5),
        hue_delta=18),
    RandomShift(prob=0.5, shift_range=(-32, 32), hide_kpts_in_shift_area=True),
    RandomHorizontalFlip(prob=0.5),
    Normalize(mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375]),
    Pad(size_divisor=32),
    ToTensor(),
]
```

3. If you want to use ```RandomCrop3D``` as it is, comment out the code below in ```train.py```. ```torch.backends.cudnn.benchmark=True``` consumed more memory in my environment. If the memory consumption decreases after commenting out the two lines of code below, I think you can try increasing the batch size.
```python
torch.backends.cudnn.enabled = True
torch.backends.cudnn.benchmark = True
```

However, please note that methods 2 and 3 may cause performance degradation.

If you encounter any other problems, please feel free to comment.
Thank You! 😊

**Comment by LionGx** [comment]
I‘ll try, thank you!!!!!
