### ISSUE TITLE
visualize the resulting images

### ISSUE THREAD

**Issue by zzHardx** [2gunsu/monocon-pytorch#21]
What tools did you use to visualize the resulting images? Like bev,3D frame

**Comment by 2gunsu** [comment]
Hello.
Only ```opencv``` was used for visualization.
The relevant codes can be found below.

https://github.com/2gunsu/monocon-pytorch/blob/9aaf1030f7c41665fd3894bb309f9d90a09d0670/engine/monocon_engine.py#L151-L194
https://github.com/2gunsu/monocon-pytorch/blob/9aaf1030f7c41665fd3894bb309f9d90a09d0670/utils/visualizer.py#L24-L250

**Comment by 2gunsu** [comment]
Close issue due to inactivity. If you have another question, feel free to reopen it.

**Comment by zzHardx** [comment]
> Hello. Only `opencv` was used for visualization. The relevant codes can be found below.
> 
> https://github.com/2gunsu/monocon-pytorch/blob/9aaf1030f7c41665fd3894bb309f9d90a09d0670/engine/monocon_engine.py#L151-L194
> 
> 
> https://github.com/2gunsu/monocon-pytorch/blob/9aaf1030f7c41665fd3894bb309f9d90a09d0670/utils/visualizer.py#L24-L250


Thank you for your reply, but I have two more questions.
1. Can I use the checkpoints I trained on other models here?
2, how to specify the visualization of a picture, like 000008.png
