### ISSUE TITLE
wonder

### ISSUE THREAD

**Issue by shanqiu24** [2gunsu/monocon-pytorch#3]
your guys removed the dependency on the mmdet package, but the details of the model are still the same as the official implementation, right?

**Comment by 2gunsu** [comment]
Hello! 

Yes, that's right. It means it's executable without installing packages like mmdet, and most of the code matches the official code as you said. In the future, we are going to customize the codes more and more to improve performance, and we are currently thinking about the idea.

**Comment by shanqiu24** [comment]
> Hello!
> 
> Yes, that's right. It means it's executable without installing packages like mmdet, and most of the code matches the official code as you said. In the future, we are going to customize the codes more and more to improve performance, and we are currently thinking about the idea.

Thanks，bro，Good job~
