### ISSUE TITLE
Hope to be able to reproduce based on Monodle code

### ISSUE THREAD

**Issue by wenjun1031** [2gunsu/monocon-pytorch#7]

**Comment by 2gunsu** [comment]
Thanks for the comment!  
But I didn't understand exactly because there was no description, could you please explain a little more in detail? 😊

**Comment by wenjun1031** [comment]
> t

Hello author, thank you very much for your contribution

Have you reproduced Monocon based on Monodle code? Because this article is based on the modification of Monodle model, and the official Monodle code is more concise. I hope to reproduce Monocon based on Monodle code, and the code will be more understandable

**Comment by 2gunsu** [comment]
Sorry for the late reply.  
As you said, the architecture proposed in this paper is based on the modification of [MonoDLE](https://openaccess.thecvf.com/content/CVPR2021/papers/Ma_Delving_Into_Localization_Errors_for_Monocular_3D_Object_Detection_CVPR_2021_paper.pdf)(CVPR, 2021).  
Compared to the [original code](https://github.com/Xianpeng919/MonoCon), the model part of this repository is almost identical, so it is reproduced based on MonoDLE.

**Comment by 2gunsu** [comment]
Due to inactivity, I close this issue.  
If you have any other questions, feel free to leave a comment here.  
Thank You. 😊
