### ISSUE TITLE
About Data Frame

### ISSUE THREAD

**Issue by zysc1996** [2gunsu/monocon-pytorch#9]
不知道up是不是中国人哈，赌一波，因为中文说的更明白一些，下面的英语是机翻。。。
我想在一个新出的数据集Rope3D上应用monocon，这个数据集是基于路侧摄像头数据的（https://thudair.baai.ac.cn/rope）。标注方式与kitti相近，但是只有一个相机，投影矩阵少很多，所以修改dataset十分困难。想请问up能否讲解一下，模型最终用到的数据包括哪些？这些数据经过层层处理，短时间确实不容易定性验证。如果您能说明一下，我就可以直接把Rope3D处理成这种格式。Deadline将近，万分期盼Orz。

I want to apply monocon on a newly released dataset, Rope3D, which is based on roadside camera data (https://thudair.baai.ac.cn/rope). The labeling is similar to kitti, but there is only one camera, so the projection matrix is much less, so it is very difficult to modify the dataset. I would like to ask UP if it is convenient to explain what data the model eventually uses includes? So that I can directly process Rope3D into this format。Deadline is coming,please...Orz

Translated with www.DeepL.com/Translator (free version)

**Comment by shanqiu24** [comment]
> 不知道up是不是中国人哈，赌一波，因为中文说的更明白一些，下面的英语是机翻。。。 我想在一个新出的数据集Rope3D上应用monocon，这个数据集是基于路侧摄像头数据的（[https://thudair.baai.ac.cn/rope）。标注方式与kitti相近，但是只有一个相机，投影矩阵少很多，所以修改dataset十分困难。想请问up能否讲解一下，模型最终用到的数据包括哪些？这些数据经过层层处理，短时间确实不容易定性验证。如果您能说明一下，我就可以直接把Rope3D处理成这种格式。Deadline将近，万分期盼Orz。](https://thudair.baai.ac.cn/rope%EF%BC%89%E3%80%82%E6%A0%87%E6%B3%A8%E6%96%B9%E5%BC%8F%E4%B8%8Ekitti%E7%9B%B8%E8%BF%91%EF%BC%8C%E4%BD%86%E6%98%AF%E5%8F%AA%E6%9C%89%E4%B8%80%E4%B8%AA%E7%9B%B8%E6%9C%BA%EF%BC%8C%E6%8A%95%E5%BD%B1%E7%9F%A9%E9%98%B5%E5%B0%91%E5%BE%88%E5%A4%9A%EF%BC%8C%E6%89%80%E4%BB%A5%E4%BF%AE%E6%94%B9dataset%E5%8D%81%E5%88%86%E5%9B%B0%E9%9A%BE%E3%80%82%E6%83%B3%E8%AF%B7%E9%97%AEup%E8%83%BD%E5%90%A6%E8%AE%B2%E8%A7%A3%E4%B8%80%E4%B8%8B%EF%BC%8C%E6%A8%A1%E5%9E%8B%E6%9C%80%E7%BB%88%E7%94%A8%E5%88%B0%E7%9A%84%E6%95%B0%E6%8D%AE%E5%8C%85%E6%8B%AC%E5%93%AA%E4%BA%9B%EF%BC%9F%E8%BF%99%E4%BA%9B%E6%95%B0%E6%8D%AE%E7%BB%8F%E8%BF%87%E5%B1%82%E5%B1%82%E5%A4%84%E7%90%86%EF%BC%8C%E7%9F%AD%E6%97%B6%E9%97%B4%E7%A1%AE%E5%AE%9E%E4%B8%8D%E5%AE%B9%E6%98%93%E5%AE%9A%E6%80%A7%E9%AA%8C%E8%AF%81%E3%80%82%E5%A6%82%E6%9E%9C%E6%82%A8%E8%83%BD%E8%AF%B4%E6%98%8E%E4%B8%80%E4%B8%8B%EF%BC%8C%E6%88%91%E5%B0%B1%E5%8F%AF%E4%BB%A5%E7%9B%B4%E6%8E%A5%E6%8A%8ARope3D%E5%A4%84%E7%90%86%E6%88%90%E8%BF%99%E7%A7%8D%E6%A0%BC%E5%BC%8F%E3%80%82Deadline%E5%B0%86%E8%BF%91%EF%BC%8C%E4%B8%87%E5%88%86%E6%9C%9F%E7%9B%BCOrz%E3%80%82)
> 
> I want to apply monocon on a newly released dataset, Rope3D, which is based on roadside camera data (https://thudair.baai.ac.cn/rope). The labeling is similar to kitti, but there is only one camera, so the projection matrix is much less, so it is very difficult to modify the dataset. I would like to ask UP if it is convenient to explain what data the model eventually uses includes? So that I can directly process Rope3D into this format。Deadline is coming,please...Orz
> 
> Translated with [www.DeepL.com/Translator](http://www.DeepL.com/Translator) (free version)

想白嫖是吧😂

**Comment by zysc1996** [comment]
我只是想解决问题。确实我之前的提问里没有说明愿意付费，这事怪我。虽然这个问题已经解决了，不过这个项目确实还有很多没看明白的地方。如果您方便的话，我愿意付费咨询。

**Comment by shanqiu24** [comment]
> 

啊哈哈😂，你是研究生吗，是在搞科研是吧，我研二的，有问题咱两直接交流啊，我也不是什么大佬，才不收钱呢😂

**Comment by zysc1996** [comment]
我是本科毕业，转行做这个做了三四年，我vx：zysc13451382687，希望能跟您交流一下

**Comment by 2gunsu** [comment]
I'm sorry for the late reply. 
I will organize the contents you requested and reply to you as soon as possible.

**Comment by zysc1996** [comment]
> I'm sorry for the late reply. I will organize the contents you requested and reply to you as soon as possible.

That's okay, the problem has been basically solved, thank you for your reply. We are currently working on the engine development, and if you are interested in working on the roadside view, you are also welcome to write to us.

**Comment by 2gunsu** [comment]
Thank you for forgiving my late reply.
Hope your project goes well. 😊
